/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.gopay.api.v3.java-conventions")
}

dependencies {
    api(libs.com.fasterxml.jackson.jaxrs.jackson.jaxrs.json.provider)
    api(project(":gp-java-api-v3-common"))
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.org.apache.httpcomponents.fluent.hc)
    api(libs.org.apache.logging.log4j.log4j.core)
    testImplementation(project(":common-tests"))
}

description = "gp-java-api-apache-http-client"

java {
    withJavadocJar()
}
