/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.gopay.api.v3.java-conventions")
}

dependencies {
    api(libs.javax.ws.rs.javax.ws.rs.api)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.org.apache.logging.log4j.log4j.core)
}

description = "gp-java-api-common"

java {
    withJavadocJar()
}
