/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.gopay.api.v3.java-conventions")
}

dependencies {
    api(project(":gp-java-api-v3-common"))
    api(libs.com.fasterxml.jackson.jaxrs.jackson.jaxrs.json.provider)
    api(libs.org.apache.cxf.cxf.rt.rs.client)
    api(libs.org.apache.cxf.cxf.rt.frontend.jaxws)
    api(libs.org.apache.cxf.cxf.rt.transports.http)
    api(libs.org.apache.cxf.cxf.rt.transports.http.jetty)
    api(libs.org.apache.cxf.cxf.api)
    api(libs.org.apache.logging.log4j.log4j.core)
    testImplementation(project(":common-tests"))
}

description = "gp-java-api-cxf"

java {
    withJavadocJar()
}
