/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.gopay.api.v3.java-conventions")
}

dependencies {
    api(libs.org.junit.jupiter.junit.jupiter.engine)
    api(libs.org.slf4j.slf4j.api)
    compileOnly(project(":gp-java-api-v3-common"))
}

description = "common-tests"
