/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.gopay.api.v3.java-conventions")
}

dependencies {
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.jboss.resteasy.resteasy.client)
    api(libs.org.jboss.resteasy.resteasy.jaxb.provider)
    api(libs.org.jboss.resteasy.resteasy.jackson2.provider)
    api(libs.org.jboss.resteasy.resteasy.multipart.provider)
    api(project(":gp-java-api-v3-common"))
    api(libs.org.apache.logging.log4j.log4j.core)
    testImplementation(project(":common-tests"))
}

description = "gp-java-api-resteasy"

java {
    withJavadocJar()
}
